server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/chat/ {
        proxy_pass http://chat-service:8080;
        proxy_set_header Host $host;
    }

    location /api/graph/ {
        proxy_pass http://graph-service:8081;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
